site_name: py-moodle
site_description: A modern Pythonic CLI and library to manage Moodle via web sessions
site_author: Ernesto Serrano
site_url: https://erseco.github.io/python-moodle/
repo_name: erseco/python-moodle
repo_url: https://github.com/erseco/python-moodle
edit_uri: edit/main/docs/
theme:
  name: material
  language: en
  favicon: images/favicon.png
  palette:
  - scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - content.code.copy
  - content.code.annotate
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - toc.follow
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
- admonition
- attr_list
- md_in_html
- toc:
    permalink: true
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
    emoji_index: !!python/name:material.extensions.emoji.twemoji ''
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path:
    - docs
    - .
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths:
        - src
        options:
          docstring_style: google
          docstring_section_style: table
          filters:
          - '!^_'
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_signature_annotations: true
          show_source: false
          signature_crossrefs: true
          summary: true
          members_order: source
          group_by_category: true
          show_category_heading: true
          show_if_no_docstring: true
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/erseco/python-moodle
    name: GitHub Repository
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/python-moodle/
    name: PyPI Package
nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quick Start: getting-started/quickstart.md
  - CLI Reference: cli.md
  - API Reference:
    - Core:
      - Session: api/session.md
      - Settings: api/settings.md
      - Auth: api/auth.md
    - Course Management:
      - Course: api/course.md
      - Category: api/category.md
      - Section: api/section.md
    - Content Modules:
      - Module: api/module.md
      - Label: api/label.md
      - Page: api/page.md
      - Resource: api/resource.md
      - Folder: api/folder.md
      - URL: api/url.md
      - SCORM: api/scorm.md
      - Assignment: api/assign.md
    - File Management:
      - Upload: api/upload.md
      - Draftfile: api/draftfile.md
    - User Management:
      - User: api/user.md
  - Examples: examples.md
  - Development: development.md
