"""Shared timeout defaults for HTTP operations."""

DEFAULT_REQUEST_TIMEOUT = 30
DEFAULT_SCRAPE_TIMEOUT = 15
DEFAULT_UPLOAD_TIMEOUT = (30, 3600)
DEFAULT_LARGE_UPLOAD_TIMEOUT = (300, 3600)

__all__ = [
    "DEFAULT_LARGE_UPLOAD_TIMEOUT",
    "DEFAULT_REQUEST_TIMEOUT",
    "DEFAULT_SCRAPE_TIMEOUT",
    "DEFAULT_UPLOAD_TIMEOUT",
]
